fprintf ('*Author: Mohamed A. Bahloul\n')
fprintf ('Research group: Estimation, Modeling and Analysis group\n')
fprintf ('Departement: Electrical and Computer Engineering Departement\n')
fprintf ('Universisty: King Abdullah_University of_Science and Technilogy\n')
fprintf ('Reference: For more details please check and cite the paper of Mohamed A.Bahloul and Taous-Meriem Laleg Kirati\n') 
fprintf ('Title: Fractional-order model representations of apparent vascular compliance as an alternative in the analysis of arterial stiffness: An in-silico study\n')
fprintf ('Journal: Physiological Measurement\n')